"""Agregar campo id_usuario_cita a Perfil

Revision ID: 317b846f8ce1
Revises: b9e25ac93f9a
Create Date: 2025-06-15 18:33:57.315429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317b846f8ce1'
down_revision = 'b9e25ac93f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meses', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('perfiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario_cita', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfiles', schema=None) as batch_op:
        batch_op.drop_column('id_usuario_cita')

    op.drop_table('configuracion')
    # ### end Alembic commands ###
