"""Agregar campo schedule_code al modelo Perfil

Revision ID: b9e25ac93f9a
Revises: 
Create Date: 2025-06-02 20:26:31.145119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e25ac93f9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfiles', schema=None) as batch_op:
        batch_op.drop_column('schedule_code')

    # ### end Alembic commands ###
